export const formulas = [
  {
    id: 1,
    formula: '$$\\sqrt{x}$$',
    latex: '\\sqrt{}',
    type: 'math',
  },
  {
    id: 2,
    formula: '$$\\frac{x}{y}$$',
    latex: '\\frac{}{}',
    type: 'math',
  },
  {
    id: 3,
    formula: '$$\\sum$$',
    latex: '\\sum_{}^{}',
    type: 'math',
    name: 'sum',
  },
  {
    id: 4,
    formula: '$$x^y$$',
    latex: '\\^{}',
    type: 'math',
  },
  {
    id: 5,
    formula: '$$x^2$$',
    latex: '\\^{2}',
    type: 'math',
  },
  {
    id: 6,
    formula: '$$x_y$$',
    latex: '\\_{}',
    type: 'math',
  },
  {
    id: 7,
    formula: '$$\\log_x y$$',
    latex: '\\log_{} {}',
    type: 'math',
  },
  {
    id: 8,
    formula: '$$\\prod$$',
    latex: '\\prod_{}^{}',
    type: 'math',
    name: 'prod',
  },
  
  {
    id: 19,
    formula: '$$\\int$$',
    latex: '\\int',
    type: 'math',
    name: 'int',
  },
  {
    id: 10,
    formula: '$$\\int_{x}^{y}$$',
    latex: '\\int',
    type: 'math',
    name: 'int',
  },
  {
    id: 11,
    formula: '$$\\oint$$',
    latex: '\\oint',
    type: 'math',
  },
  {
    id: 12,
    formula: '$$\\lim_{x\\to y}$$',
    latex: '\\lim_{{x} \\to {}}',
    type: 'math',
  },
  {
    id: 13,
    formula: '$$\\lim_{x\\to \\infty}$$',
    latex: '\\lim_{{x} \\to \\infty}',
    type: 'math',
  },
  {
    id: 14,
    formula: '$$\\pi$$',
    latex: '\\pi',
    type: 'math',
  },
  {
    id: 15,
    formula: '$$\\infty$$',
    latex: '\\infty',
    type: 'math',
  },
  {
    id: 16,
    formula: '$$\\to$$',
    latex: '\\to',
    type: 'math',
  },
];
